
.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2003-2021 Akito Tajitsu <akito.tajitsu@nao.ac.jp>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.IX Title "HOE 1"
.TH HOE 1 "September 24, 2021" "5.5.9" "User Manuals"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hoe \- Subaru HDS++ OPE file Editor
.SH SYNOPSIS
.B hoe
.RI [ options ]
.SH DESCRIPTION
\fBhoe\fP is a Gtk+2/3 based GUI program to prepare observations on 
High Dispersion Spectrograph (HDS) and several other instruments of
8.2-m Subaru Telescope, National Astronomical Observatory of Japan.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
Its fundamental purpose is to make operation (OPE) files and service
proposal requests for your observations at Subaru Telescope.
Furthermore, it works as a finding chart (FC) creator, 
an Echelle format simulator (EFS), an exposure time calculator (ETC),
and a query tool for various archiving databases.


.SH "INSTRUMENTS of Subaru Telescope"
Currently supported instruments are
.TP
.B HDS
High Dispersion Spectrograph
.TP
.B IRCS
InfraRed Camera and Spectrograph
.TP
.B HSC
Hyper Spurime-Cam.
.TP
.B IRD
InfraRed Doppler.


.SH "OPTIONS"
This program follows the usual GNU command line syntax.
.TP
.B \-h, \-\-help
Print help message.
.TP
.B \-i, \-\-input  [input\-CSV\-file]
Set an input object list file.
.TP
.B \-c, \-\-config  [config\-file]
Load a config (.hoe / .shoe) file.
.TP
.B \-d, \-\-debug
Print out debugging network messages for developpers


.SH "AUTHOR"
.nf
Akito Tajitsu	<akito.tajitsu@nao.ac.jp>
  Subaru Telescope, National Astronomical Observatory of Japan
.br
  URL:   https://www.naoj.org/Observing/Instruments/HDS/hoe/
.fi

